<a href="https://colab.research.google.com/github/Shubhangi5785317/shubhangi-AnalyticsEngineering/blob/main/maths/simple_maths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create Database

In [ ]:
import sqlite3
import pandas as pd

# Create or connect to a database file
conn = sqlite3.connect("shop.db")
cur = conn.cursor()

print("Database connected successfully.")

Database connected successfully.

Create simple Table

In [ ]:
cur.execute("""
CREATE TABLE IF NOT EXISTS sales (
    sale_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT,
    category TEXT,
    price REAL,
    quantity INTEGER
);
""")

conn.commit()
print("Table created.")

Table created.

In [17]:
cur.execute("DELETE FROM sales;") #prevents duplication of rows in the table
conn.commit()

Insert sample data

In [18]:
cur.executemany("""
INSERT INTO sales (product_name, category, price, quantity)
VALUES (?, ?, ?, ?);
""", [
    ('Laptop', 'Electronics', 800, 2),
    ('Phone', 'Electronics', 500, 3),
    ('Headphones', 'Electronics', 100, 5),
    ('Desk Chair', 'Furniture', 150, 4),
    ('Desk', 'Furniture', 300, 2),
    ('Notebook', 'Stationery', 5, 20),
    ('Pen Pack', 'Stationery', 10, 10)
])

conn.commit()
print("Data inserted.")

Data inserted.

View all data

In [19]:
df = pd.read_sql_query("SELECT * FROM sales", conn)
df

   sale_id product_name     category  price  quantity
0       22       Laptop  Electronics  800.0         2
1       23        Phone  Electronics  500.0         3
2       24   Headphones  Electronics  100.0         5
3       25   Desk Chair    Furniture  150.0         4
4       26         Desk    Furniture  300.0         2
5       27     Notebook   Stationery    5.0        20
6       28     Pen Pack   Stationery   10.0        10

Calculate the AVG Price

In [20]:
pd.read_sql_query(""" SELECT AVG(Price) FROM sales """, conn)

   AVG(Price)
0  266.428571

Calculate Total Quantity Sold

In [21]:
pd.read_sql_query(""" SELECT SUM(quantity) FROM Sales """, conn)

   SUM(quantity)
0             46

Calculate Highest and Lowest Price

In [23]:
pd.read_sql_query(""" SELECT MAX(Price) MIN(Price) FROM Sales """, conn)

   MAX(Price)  MIN(Price)
0       800.0         5.0

Calculate revenue per product

In [28]:
pd.read_sql_query(""" SELECT product_name (Price*quantity) As Revenue FROM Sales """, conn)

  product_name  Revenue
0       Laptop   1600.0
1        Phone   1500.0
2   Headphones    500.0
3   Desk Chair    600.0
4         Desk    600.0
5     Notebook    100.0
6     Pen Pack    100.0

Calculate total revenue

In [31]:
pd.read_sql_query("""SELECT SUM(Price*quantity) As Total_Revenue FROM Sales """, conn)

   Total_Revenue
0         5000.0

Calculate revenue per category

In [41]:
pd.read_sql_query(""" SELECT category,SUM(Price*quantity) As Revenue FROM Sales GROUP BY category """, conn)

      category  Revenue
0  Electronics   3600.0
1    Furniture   1200.0
2   Stationery    200.0

Calculate average price per category

In [37]:
pd.read_sql_query(""" SELECT category, AVG(Price) FROM Sales GROUP BY category """, conn)

      category  AVG(Price)
0  Electronics  466.666667
1    Furniture  225.000000
2   Stationery    7.500000

Calculate count products per category

In [39]:
pd.read_sql_query(""" SELECT category, COUNT(Product_name) As Product_Count FROM Sales Group By Category """, conn)

      category  Product_Count
0  Electronics              3
1    Furniture              2
2   Stationery              2

Which category has a revenue greater than 2000

In [45]:

pd.read_sql_query(""" SELECT category,SUM(Price*quantity) As Revenue FROM Sales GROUP BY category HAVING Revenue > 2000 """, conn)

      category  Revenue
0  Electronics   3600.0